all:
	g++ test_predictor.cpp -o tp.o -lsndfile
	g++ test_reverse_predictor.cpp -o tr.o -lsndfile
	g++ test_predictor2.cpp -o tp2.o -lsndfile	
	g++ test_reverse_predictor2.cpp -o tr2.o -lsndfile
clean:
	rm metadata
	rm encoded
	rm *.o

